name: Synchronisation automatique vers le Compte B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Empêche l'utilisation du robot par défaut

      - name: Pousser vers le dépôt de destination
        env:
          DEST_TOKEN: ${{ secrets.DESTINATION_TOKEN }}
          DEST_REPO: "remyagaguy/cultiso"
        run: |
          if [ -z "$DEST_TOKEN" ]; then
            echo "Erreur: Le secret DESTINATION_TOKEN est vide ou introuvable !"
            exit 1
          fi
          git remote add destination https://x-access-token:${DEST_TOKEN}@github.com/${DEST_REPO}.git
          git push destination main --force
